config/routes.rb
Rails.application.routes.draw do
  resources :markers
  resources :maps
  namespace :admin do
    resources :users
    root to: "users#index"
  end
  root to: 'maps#index'
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/map.rb
class Map < ApplicationRecord
  validates_presence_of :lat1, :lng1, :lat2, :lng2

  acts_as_paranoid column: :destroyed_at

  belongs_to  :user
  has_many    :markers

  # https://www.mapbox.com/mapbox-gl-js/api/#LngLatBoundsLike
  def bounds
    [[lng1, lat1], [lng2, lat2]]
  end
end

app/models/marker.rb
class Marker < ApplicationRecord
  validates_presence_of :lng, :lat

  acts_as_paranoid column: :destroyed_at

  belongs_to :user
  belongs_to :map

  def coordinates
    [lng, lat]
  end
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?

  has_many :maps
  has_many :markers

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_admin

    def authenticate_admin
      # TODO Add authentication logic here.
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_map, only: [:show, :edit, :update, :destroy]

  # GET /maps
  # GET /maps.json
  def index
    @maps = current_user.maps.all
  end

  # GET /maps/1
  # GET /maps/1.json
  def show
  end

  # GET /maps/new
  def new
    @map = current_user.maps.new
  end

  # GET /maps/1/edit
  def edit
  end

  # POST /maps
  # POST /maps.json
  def create
    @map = current_user.maps.new(map_params)

    respond_to do |format|
      if @map.save
        format.html { redirect_to edit_map_path(@map), notice: 'Map was successfully created.' }
        format.json { render :show, status: :created, location: @map }
      else
        format.html { render :new }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maps/1
  # PATCH/PUT /maps/1.json
  def update
    respond_to do |format|
      if @map.update(map_params)
        format.html { redirect_to @map, notice: 'Map was successfully updated.' }
        format.json { render :show, status: :ok, location: @map }
      else
        format.html { render :edit }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maps/1
  # DELETE /maps/1.json
  def destroy
    @map.destroy
    respond_to do |format|
      format.html { redirect_to maps_url, notice: 'Map was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_map
      @map = current_user.maps.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def map_params
      params.require(:map).permit(:lat1, :lng1, :lat2, :lng2, :name, :zoom)
    end
end

app/controllers/markers_controller.rb
class MarkersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_marker, only: [:show, :edit, :update, :destroy]

  # GET /markers
  # GET /markers.json
  def index
    @markers = current_user.markers.all
  end

  # GET /markers/1
  # GET /markers/1.json
  def show
  end

  # GET /markers/new
  def new
    @map    = current_user.markers.find(params[:map_id])
    @marker = current_user.markers.new(map_id: @map.id)
  end

  # GET /markers/1/edit
  def edit
  end

  # POST /markers
  # POST /markers.json
  def create
    @marker = Marker.new(marker_params)

    respond_to do |format|
      if @marker.save
        format.html { redirect_to @marker, notice: 'Marker was successfully created.' }
        format.json { render :show, status: :created, location: @marker }
      else
        format.html { render :new }
        format.json { render json: @marker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /markers/1
  # PATCH/PUT /markers/1.json
  def update
    respond_to do |format|
      if @marker.update(marker_params)
        format.html { redirect_to @marker, notice: 'Marker was successfully updated.' }
        format.json { render :show, status: :ok, location: @marker }
      else
        format.html { render :edit }
        format.json { render json: @marker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /markers/1
  # DELETE /markers/1.json
  def destroy
    @marker.destroy
    respond_to do |format|
      format.html { redirect_to markers_url, notice: 'Marker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marker
      @map    = current_user.markers.find(params[:map_id])
      @marker = current_user.markers.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def marker_params
      params.require(:marker).permit(:map_id, :name, :description, :residents, :lat, :lng, :icon)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/maps_helper.rb
module MapsHelper

  def map_image_url(map, options={})
    opts = {
        token:  Settings.mapbox.access_token,
        height: options[:height] || 125,
        width:  options[:height] || 125,
        style:  options[:style]  || 'streets',
        lng:    (map.lng2 + map.lng1)/2,
        lat:    (map.lat2 + map.lat1)/2,
        zoom:   map.zoom || 5,
    }
    "https://api.mapbox.com/v4/mapbox.%{style}/%{lng},%{lat},%{zoom}/%{width}x%{height}.png?access_token=%{token}" % opts
  end


  # {
  #     "type": "Feature",
  #     "properties": {
  #         "description": "<strong>Some</strong><p> long description with HTML in it.</p>",
  #         "icon": "theatre"
  #     },
  #     "geometry": {
  #         "type": "Point",
  #         "coordinates": [-77.038659, 38.931567]
  #     }
  # }
  def geojson_feature_collection(map_id, markers)
    markers.map do |marker|
       {
          type: 'Feature',
          geometry: {
              type: 'Point',
              coordinates: marker.coordinates
          },
          properties: {
              # https://www.mapbox.com/maki-icons/
              icon:        'music' || marker.icon.presence || 'marker',
              map_id:      map_id,
              marker_id:   marker.id,
              title:       marker.name,
              description: marker.description,
              'color': '#3bb2d0',
              'size':  'large',
          }
      }
    end
  end
end

app/helpers/markers_helper.rb
module MarkersHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li class='nav-item'><%= link_to 'Edit account', edit_user_registration_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete', class: 'nav-link' %></li>
<% else %>
  <li class='nav-item'><%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 4.0 %>
<div class="container">
  <nav class="navbar navbar-fixed-top navbar-dark bg-inverse">
    <ul class="nav navbar-nav clearfix">
      <li class="nav-item">
        <button class="navbar-toggler hidden-sm-up nav-link" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2" aria-controls="exCollapsingNavbar2" aria-expanded="false" aria-label="Toggle navigation">
          &#9776;
        </button>
      </li>
    </ul>
    <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
      <%= link_to "My Maps", root_path, class: 'navbar-brand' %>
      <%= link_to "New Map", new_map_path, class: 'navbar-brand' %>
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>

      <ul class="nav navbar-nav float-sm-right">
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Oneconcern Indika" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Oneconcern Indika" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'maps', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
    <script src='https://api.mapbox.com/mapbox-gl-js/v0.28.0/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v0.28.0/mapbox-gl.css' rel='stylesheet' />
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main" class="main_area">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/maps/_form.html.erb
<%= form_for(map) do |f| %>
  <%= f.hidden_field :zoom %>

  <% if map.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(map.errors.count, "error") %> prohibited this map from being saved:</h2>

      <ul>
      <% map.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group">
      <%= f.label :name%>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-inline my-1">
      <div class="form-group mr-1">
        <%= f.label :lat1 %>
        <%= f.text_field :lat1, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :lng1 %>
        <%= f.text_field :lng1, class: 'form-control' %>
      </div>
    </div>

    <div class="form-inline my-1">
      <div class="form-group mr-1">
        <%= f.label :lat2 %>
        <%= f.text_field :lat2, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :lng2 %>
        <%= f.text_field :lng2, class: 'form-control' %>
      </div>
    </div>

    <%= f.submit class: 'btn btn-primary my-1' %>
<% end %>

app/views/maps/_map_modal.html.erb
<% # Modal %>
<div class="modal fade" id="mapModal" tabindex="-1" role="dialog" aria-labelledby="mapModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="mapModalLabel">Marker Details</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>


<% # Button trigger modal %>
<% if false %>
  <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#mapModal">
    Launch demo modal <%= @map.name %>
  </button>
<% end %>

app/views/maps/_map_view.html.erb
<div class="row">
  <div id='map' class="col-sm-12 col-lg-7 px-0"></div>

  <% if editable %>
  <ul class="list-unstyled col-sm-12 col-lg-5">
    <li>
      Specify the Long-Lat bounding box by clicking and holding <key>Shift</key> while dragging the mouse pointer.
    </li>
    <li>
      The Long-Lat input fields will be updated when you release the mouse button.
    </li>
  </ul>
  <% end %>

</div>

<script>
  $(document).ready(function(){
    var accessToken = '<%= Settings.mapbox.access_token %>';
    var mapBounds   = <%= map.bounds.to_json %>;
    var geojson     = <%= geojson_feature_collection(map.id, map.markers).to_json.html_safe %>;
    var options     = {
        editable: <%= editable.to_json.html_safe %>,
        newMap:   <%= map.new_record?.to_json.html_safe %>
    };
    window.mapHandler = new window.MapHandler('map', accessToken, mapBounds , geojson, options);
  });
</script>

<%= render :partial => "map_modal" %>

app/views/maps/edit.html.erb
<h1>Editing Map</h1>

<%= render 'map_view', map: @map, editable: true %>

<%= render 'form', map: @map %>

<div class="my-1">
  <%= link_to 'Show', @map,       class: 'btn btn-primary mr-1' %>
  <%= link_to 'Back', maps_path,  class: 'btn btn-secondary' %>
</div>

app/views/maps/index.html.erb
<h1>Maps</h1>

<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>ID</th>
      <th>Name</th>
      <th class="text-right">Lng1</th>
      <th class="text-right">Lat1</th>
      <th class="text-right">Lng2</th>
      <th class="text-right">Lat2</th>
    </tr>
  </thead>

  <tbody>
    <% @maps.each do |map| %>
      <tr>
        <td class="mapcell"><%= link_to(map){ image_tag map_image_url(map), alt: '', class: 'mapimage'} %></td>
        <td><%= link_to map.id,   map_path(map) %></td>
        <td><%= link_to map.name || '', map_path(map) %></td>
        <td class="text-right text-truncate map_lng_lat"><%= map.lng1 %></td>
        <td class="text-right text-truncate map_lng_lat"><%= map.lat1 %></td>
        <td class="text-right text-truncate map_lng_lat"><%= map.lng2 %></td>
        <td class="text-right text-truncate map_lng_lat"><%= map.lat2 %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Map', new_map_path, class: 'btn btn-primary my-2' %>

app/views/maps/new.html.erb
<h1>New Map</h1>

<%= render 'map_view', map: @map, editable: @map.new_record? %>


<%= render 'form', map: @map %>

<%= link_to 'Back', maps_path, class: 'btn btn-secondary my-1' %>

app/views/maps/show.html.erb
<%= render 'map_view', map: @map, editable: false %>

<h2 class="mt-2"><%= @map.name %></h2>


<div class="card">
  <div class="card-header">
    Map Details
    <div class="float-sm-right">
      <%= link_to 'Edit', edit_map_path(@map), class: 'btn btn-primary mr-1' %>
      <%= link_to 'Destroy Map', @map, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger mr-1' %>
    </div>
  </div>

<dl class="row card-block map-details my-2 float-right">
  <dt class="col-sm-2">Map ID</dt>
  <dd class="col-sm-10"><%= @map.id %></dd>
  <dt class="col-sm-2">Created At</dt>
  <dd class="col-sm-10"><%= @map.created_at %></dd>
  <dt class="col-sm-2">Updated At</dt>
  <dd class="col-sm-10"><%= @map.updated_at %></dd>
  <dt class="col-sm-2">SW Corner</dt>
  <dd class="col-sm-3">Lng: <%= @map.lng1 %></dd>
  <dd class="col-sm-3">Lat: <%= @map.lat1 %></dd>
  <dt class="col-sm-2">NE Corner</dt>
  <dd class="col-sm-3">Lng: <%= @map.lng2 %></dd>
  <dd class="col-sm-3">Lat: <%= @map.lat2 %></dd>
</dl>

</div>



<div class="card mb-3">
  <div class="card-header">
    Map Markers
  </div>

<table class="card-block table">
  <thead>
  <tr>
    <th class="text-right">Marker ID</th>
    <th class="text-right">Name</th>
    <th class="text-right">Residents</th>
    <th class="text-right">Longitude</th>
    <th class="text-right">Latitude</th>
  </tr>
  </thead>

  <tbody>
  <% @map.markers.each do |marker| %>
      <tr>
        <td class="text-right"><%= marker.id        %></td>
        <td class="text-right"><%= link_to marker.name, 'javascript:void(0)', class: 'marker_link' %></td>
        <td class="text-right"><%= marker.residents %></td>
        <td class="text-right"><%= marker.lng       %></td>
        <td class="text-right"><%= marker.lat       %></td>
      </tr>
  <% end %>
  </tbody>
</table>

</div>



<div class="row my-2">
  <%= link_to 'My Maps', maps_path, class: 'btn btn-secondary' %>
</div>

app/views/markers/_form.html.erb
<%= form_for(marker) do |f| %>
  <% if marker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(marker.errors.count, "error") %> prohibited this marker from being saved:</h2>

      <ul>
      <% marker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :map_id %>
    <%= f.text_field :map_id %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :residents %>
    <%= f.number_field :residents %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/markers/edit.html.erb
<h1>Editing Marker</h1>

<%= render 'form', marker: @marker %>

<%= link_to 'Show', @marker %> |
<%= link_to 'Back', markers_path %>

app/views/markers/index.html.erb
<h1>Markers</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Map</th>
      <th>Name</th>
      <th>Description</th>
      <th>Residents</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @markers.each do |marker| %>
      <tr>
        <td><%= marker.user %></td>
        <td><%= marker.map %></td>
        <td><%= marker.name %></td>
        <td><%= marker.description %></td>
        <td><%= marker.residents %></td>
        <td><%= link_to 'Show', marker %></td>
        <td><%= link_to 'Edit', edit_marker_path(marker) %></td>
        <td><%= link_to 'Destroy', marker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Marker', new_marker_path %>

app/views/markers/new.html.erb
<h1>New Marker</h1>

<%= render 'form', marker: @marker %>

<%= link_to 'Back', markers_path %>

app/views/markers/show.html.erb
<p>
  <strong>User:</strong>
  <%= @marker.user %>
</p>

<p>
  <strong>Map:</strong>
  <%= @marker.map %>
</p>

<p>
  <strong>Name:</strong>
  <%= @marker.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @marker.description %>
</p>

<p>
  <strong>Residents:</strong>
  <%= @marker.residents %>
</p>

<%= link_to 'Edit', edit_marker_path(@marker) %> |
<%= link_to 'Back', markers_path %>